name: Terraform Validate

on: 
  workflow_call:
    inputs:
        tfpath:
            description: 'TF File Path'    
            type: string 
            required: true
            default: 'infra'

jobs:
  tf_code_check:
    name: Terraform Validation 
    runs-on: ubuntu-latest

    if:  ${{ inputs.tfpath }} 
    steps:
    - uses: actions/checkout@v2.5.0
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2
      with: 
        terraform_version: 0.14.0  # yes we wanna hardcode this as we dont want people setting their own

    - name: Terraform Validate
      working-directory: ${{ github.event.inputs.tfpath }}
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        echo "** Running Terraform Init**"
        terraform init -backend=false
        echo "** Running Terraform Validate**"
        terraform validate
        


    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Test with Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ inputs.tfpath }}
        framework: terraform 

    